### ISSUE TITLE
关于分类

### ISSUE THREAD

**Issue by lorre-0322** [clark-cui/vitepress-blog-zaun#18]
大佬你好，请问怎么根据posts里面的文件夹名字自动生成分类呢，这样就不用每次都在文章里再加上分类了，文章也好归纳。

**Comment by clark-cui** [comment]
写个node脚本就行，代码我放这里了https://github.com/clark-cui/writeScripts/tree/master

**Comment by lorre-0322** [comment]
> 写个节点脚本就行，代码我放这里了https://github.com/clark-cui/writeScripts/tree/master
好的，谢谢哥！
