### ISSUE TITLE
博客会展示未经允许的内容

### ISSUE THREAD

**Issue by charleschetty** [clark-cui/vitepress-blog-zaun#20]
如题，我自己测试时候会展示node_modules中的md文件

![](https://raw.githubusercontent.com/charleschetty/picturebed/main/picture/Screenshot_20221111_225242.png)

demo里面会显示readme文件：https://visionary-sunflower-dc7ae3.netlify.app/readme.html

**Comment by clark-cui** [comment]
这个是正常行为，你不去主动访问这个node_modules地址，vitepress就不会就打包他的服务。目的是为了保留开发环境下多目录的服务启动。对于这种静态生成器，在生产环境都是构建产物，所以也不会有node_modules目录的情况。
如果你不想要node_modules存在，.gitignore里设置git提交忽略。本地package.json里scripts字段 dev的command里加上指定目录即可，例如我这里的posts目录，就是vitepress dev posts

**Comment by charleschetty** [comment]
感谢回答，我本来是打算加一个搜索插件，结果搜索结果显示了node_modules中的内容，那看来是我配置的问题，感谢。

**Comment by clark-cui** [comment]
不客气，我这个好久没维护了。之前vitepress默认的模板很丑，所以我自己写了个。现在vitepress默认的主题就不错，推荐直接用[vitepress官网那个模板](https://vitepress.vuejs.org/guide/getting-started)吧，搜索的话可以接入[algolia](https://www.algolia.com/),他有自己写好的包，微调下样式就行
