### ISSUE TITLE
markdown-it 配置出错

### ISSUE THREAD

**Issue by Forsworns** [clark-cui/vitepress-blog-zaun#21]
老哥的配色很好看啊，

但是 `.vitepress/config.ts` 里面的 markdown-it 配置出错了，不应该放到 ThemeConfig 里面，应该在 AppConfigs 里

```typescript
markdown: {
  config: (md) => {
    md.use(highlightjs);
  },
},
```

**Comment by clark-cui** [comment]
🙏感谢指出，现在这版vitepress默认的markdown配置已经足够了，所以我把markdown-it-highlightjs移除了

**Comment by Forsworns** [comment]
hh 我是用 markdown-it-katex 的时候发现加不上去
